### ISSUE TITLE
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes

### ISSUE THREAD

**Issue by meetwudi** [qiniu/nodejs-sdk#123]
I am using [node-webkit](https://github.com/rogerwang/node-webkit) with qiniu/nodejs-sdk. I am uploading an 7KB image with following code, almost identical to the code in examples.

```
  function getUploadToken(bucketName) {
    var putPolicy = new qiniu.rs.PutPolicy(bucketName);
    return putPolicy.token();
  }
  function uploadFile(localFile, key) {
    var extra = new qiniu.io.PutExtra(),
      token = getUploadToken($('#bucket_name').val());

    qiniu.io.putFile(token, key, localFile, extra, function(err, ret) {
      if(!err) {
        console.log(ret.key, ret.hash);
      } else {
        console.log(err);
      }
    });
  }
```

But when I try to upload the image, I got a _RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes_. 
![screen shot 2014-11-03 at 6 39 25 pm](https://cloud.githubusercontent.com/assets/5257816/4881169/b3b4e636-6345-11e4-909d-88024786df3f.png)

**Comment by douxing** [comment]
@longbai @fengmk2 this bug has NOT been fixed because [your package.json file still use 0.0.7 version of formstream](https://github.com/qiniu/nodejs-sdk.v6/blob/master/package.json#L59), will you update it to the latest version of formstream, to make qiniu node sdk suports number fields?

**Comment by longbai** [comment]
@douxing 我们看下

**Comment by douxing** [comment]
@longbai  感谢
