### ISSUE TITLE
感觉生成uploadtoken有问题，Android端报401

### ISSUE THREAD

**Issue by Hi-Rube** [qiniu/nodejs-sdk#128]
qn  中得uploadtoken 产生函数
exports.uploadToken = function uploadToken(options) {
  options = options || {};
  options.scope = options.scope || this.options.bucket;
  options.deadline = options.deadline || (utility.timestamp() + 3600);
  var flags = options;
  // 步骤2：将 Flags 进行安全编码
  var encodedFlags = utility.base64encode(JSON.stringify(flags), true);

  // 步骤3：将编码后的元数据混入私钥进行签名
  // 步骤4：将签名摘要值进行安全编码
  var encodedSign = this.signData(encodedFlags);

  // 步骤5：连接各字符串，生成上传授权凭证
  return this.options.accessKey + ':' + encodedSign + ':' + encodedFlags;
};

**Comment by Hi-Rube** [comment]
这个就直接200

**Comment by iyjian** [comment]
我也是哦．．．．　没人回答么？

**Comment by longbai** [comment]
@iyjian 请麻烦告知下 nodejs 的版本号

**Comment by Hi-Rube** [comment]
@longbai
exports.uploadToken = function uploadToken(options) {
options = options || {};
options.scope = options.scope || this.options.bucket;
options.deadline = options.deadline || (utility.timestamp() + 3600);
var flags = options;
// 步骤2：将 Flags 进行安全编码
var encodedFlags = utility.base64encode(JSON.stringify(flags), true);

// 步骤3：将编码后的元数据混入私钥进行签名
// 步骤4：将签名摘要值进行安全编码
var encodedSign = this.signData(encodedFlags);

// 步骤5：连接各字符串，生成上传授权凭证
return this.options.accessKey + ':' + encodedSign + ':' + encodedFlags;
};   这样生成是对的

**Comment by longbai** [comment]
您贴的这个过程看起来是对的。 您是用PutPolicy(...) 这个函数出错的么？

**Comment by Hi-Rube** [comment]
@longbai
大半年过去了都忘了，，，最近代码更新过了，没试过。  应该是获取token不对
