### ISSUE TITLE
fetch 不返回结果

### ISSUE THREAD

**Issue by BiteBit** [qiniu/nodejs-sdk#131]
你好，我在使用fetch服务时遇到了问题
fetch 图片 http://image.beekka.com/blog/2015/bg2015022204.gif
大小 2.3mb
需要很久才可以返回，有时甚至不返回。
导致程序一直在等待返回，能支持超时操作吗？
API 无论如何请保证返回结果给用户
文件太大无法下载或者下载超时，也该返回给用户一个错误
请问有什么解决方案吗？

**Comment by arifeng** [comment]
同求

**Comment by longbai** [comment]
可以在sdk这端设置超时

**Comment by BiteBit** [comment]
exports.RPC_TIMEOUT = 3600000; // default rpc timeout: one hour
不好意思。我没有看到有这个选项。刚测试了下。设置超时有效。
默认时间为什么是一小时这么长
