### ISSUE TITLE
qiniu.io.put　失败

### ISSUE THREAD

**Issue by yjhjstz** [qiniu/nodejs-sdk#144]
12 Jun 11:04:52 - { code: -1,
  error: { [ConnectionTimeoutError: Request#94 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:52 - { code: -1,
  error: { [ConnectionTimeoutError: Request#95 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:52 - { code: -1,
  error: { [ConnectionTimeoutError: Request#96 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#97 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#98 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#99 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#100 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#101 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#102 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#103 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#104 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#105 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#106 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:53 - { code: -1,
  error: { [ConnectionTimeoutError: Request#107 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:54 - { code: -1,
  error: { [ConnectionTimeoutError: Request#108 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:54 - { code: -1,
  error: { [ConnectionTimeoutError: Request#109 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:54 - { code: -1,
  error: { [ConnectionTimeoutError: Request#110 timeout for 5000ms] name: 'ConnectionTimeoutError' } }
12 Jun 11:04:55 - { code: -1,
  error: { [ConnectionTimeoutError: Request#111 timeout for 5000ms] name: 'ConnectionTimeoutError' } }

**Comment by longbai** [comment]
连接服务器失败，麻烦您提下工单，由技术支持人员进行详细排查。
