### ISSUE TITLE
master上的分支与SDK文档不匹配

### ISSUE THREAD

**Issue by jinphen** [qiniu/nodejs-sdk#154]
sdk文档中描述：var conn = new qiniu.digestauth.Client(); master上代码无digistauth。

**Comment by NepLiang** [comment]
官网文档并未有var conn = new qiniu.digestauth.Client()；说明，文档是在哪里看到的？
官网文档地址：
http://developer.qiniu.com/docs/v6/sdk/nodejs-sdk.html

**Comment by jinphen** [comment]
在这里看到的 http://docs.qiniutek.com/v3/sdk/nodejs/

在npm的readme上没有看到你帖的地址

**Comment by NepLiang** [comment]
http://docs.qiniutek.com/v3/sdk/nodejs/ 这是v3版本的说明，可以查看分支，建议使用v6版本

**Comment by jinphen** [comment]
嗯，已经在使用v6了。 :)

**Comment by peaceful321** [comment]
ok, 如果有问题，也还可以直接通过工单 将问题反馈给我们；

**Comment by jemygraw** [comment]
已解决，发布v7.0.2
