### ISSUE TITLE
七牛 node-sdk上传图片出错write EPIPE

### ISSUE THREAD

**Issue by kuixiansheng** [qiniu/nodejs-sdk#159]
七牛通过node-sdk上传图片出现这个错误write EPIPE。
个人猜测是图片过大的问题。如果是图片过大，怎么处理这个问题？

**Comment by longbai** [comment]
收到，我们看下

**Comment by jemygraw** [comment]
可以使用分片上传，https://github.com/qiniu/nodejs-sdk/blob/master/examples/resume_upload_simple.js
