### ISSUE TITLE
上传文件502

### ISSUE THREAD

**Issue by wind108369** [qiniu/nodejs-sdk#163]
根据sdk写了一个node脚本，大部分文件都上传成功，有一个js有6M大，上传时候502，请问有什么解决方法

**Comment by longbai** [comment]
能麻烦给下详细的日志么，另外麻烦ping下 upload.qiniu.com 看下

**Comment by wind108369** [comment]
上传的方法
![image](https://cloud.githubusercontent.com/assets/1305983/13589642/5c555504-e514-11e5-9ad1-acdd9971f571.png)

错误log（前两个上传成功了，最后一个失败了）
![image](https://cloud.githubusercontent.com/assets/1305983/13589607/11028626-e514-11e5-8484-11c68c39face.png)

ping
![image](https://cloud.githubusercontent.com/assets/1305983/13589630/44d461f4-e514-11e5-8c5d-b703abf8079e.png)

**Comment by zjkyz8** [comment]
遇到了相同的问题，并不是所有上传的文件都报错，只是一部分文件会失败报错

**Comment by peaceful321** [comment]
502 是 Bad Gateway 错误的网关；
可能是网络不稳定造成的，这种问题最好第一时间能够提工单，
反馈给技术支持，将ping 域名的截图发一下，我们会尽快帮忙排查处理的；
