### ISSUE TITLE
缺少功能

### ISSUE THREAD

**Issue by dinfer** [qiniu/nodejs-sdk#167]
没有列举资源(list)
另: endUser的使用API在手册里没有.

**Comment by songfei9315** [comment]
1，https://github.com/qiniu/nodejs-sdk.v6/blob/199342c4a77aa55bd522005cc7cd451478593123/qiniu/rsf.js
2，
http://developer.qiniu.com/article/developer/security/put-policy.html#格式
![image](https://cloud.githubusercontent.com/assets/13344251/14662495/3c28c152-06e9-11e6-8cb4-6ccb3d663550.png)

**Comment by linesh-simplicity** [comment]
楼上点赞，刚也用上了list的功能。

不过资源列举也确实没有在 [文档资源管理这块](http://developer.qiniu.com/code/v6/sdk/nodejs.html#rs) 列出，而 [这份API Specification](http://developer.qiniu.com/code/v6/api/kodo-api/rs/list.html)中虽列出了API规范，但并未交代该API这个qiniu-nodejs-sdk中的用法。主页文档能再改进下就更好了。

**Comment by peaceful321** [comment]
你好，这边主要是研发的同事 和 项目经理来维护的；

**Comment by peaceful321** [comment]
后续有问题，可以直接通过工单联系七牛的技术支持，每天都会有人解决的；

**Comment by jemygraw** [comment]
已支持，v7.0.2
