### ISSUE TITLE
上传大文件的时候报错

### ISSUE THREAD

**Issue by madfrog2047** [qiniu/nodejs-sdk#173]
上传1.9G的文件的时候，使用putFile方法上传报错
使用node 5.9.0的时候
![image](https://cloud.githubusercontent.com/assets/16751056/13948185/9c72cb08-f059-11e5-8c2f-4a6944ad2f59.png)

使用0.10.40的时候
![image](https://cloud.githubusercontent.com/assets/16751056/13948221/e9a35410-f059-11e5-9a58-3cdae76268d1.png)

**Comment by plusmancn** [comment]
目测需要用到 `Stream`，通过 [上传片](http://developer.qiniu.com/code/v6/api/kodo-api/up/bput.html) 进行上传。

**Comment by peaceful321** [comment]
同楼上；
可以去七牛的portal平台提交工单联系七牛的技术支持，周末都有人会回复处理问题的

**Comment by meteormatt** [comment]
现在的这个SDK不能上传大于1G的文件。因为七牛的表单上传限制 1G。需要用分片上传，可是这个SDK还不支持。
http://sfau.lt/bNDLGf

**Comment by jemygraw** [comment]
fixed in v7.0.2 https://github.com/qiniu/nodejs-sdk/blob/master/examples/resume_upload_simple.js

**Comment by meteormatt** [comment]
貌似上传的文件名不是指定的**fname**

**Comment by jemygraw** [comment]
是指定的key参数，不是fname

**Comment by meteormatt** [comment]
例子里是**fname**

**Comment by jemygraw** [comment]
七牛的key都是放到方法参数里面的，那个可选参数表示你可以设置fname

**Comment by jemygraw** [comment]
这个需要结合文档看下就可以了，七牛的文件名都是用key来表示，因为空间里面的文件名是唯一的。

**Comment by meteormatt** [comment]
putFile的时候不能传**null**,要传**key**咯？

**Comment by meteormatt** [comment]
```bash
write resume record progress.log
400
{ error: 'block 21: unexpected block size 3344566' }
```
传大文件依然报错。

https://gist.github.com/meteormatt/061c076443c30cd96dcbcdfbfe998c7d

**Comment by jemygraw** [comment]
putFile的key可以为null，默认会用文件的hash做文件名

**Comment by jemygraw** [comment]
>write resume record progress.log
400
{ error: 'block 21: unexpected block size 3344566' }

这个重试可以成功么？

**Comment by meteormatt** [comment]
重试还是失败。测试代码已给，就运行了一遍。

**Comment by meteormatt** [comment]
progress.log删除了之后可以了。可能之前不同文件残留的progress.log

**Comment by jemygraw** [comment]
en，这个进度文件需要和所要上传的文件关联，那个只是一个demo
