### ISSUE TITLE
此sdk能否增加stream流上传的功能

### ISSUE THREAD

**Issue by nouh** [qiniu/nodejs-sdk#182]

**Comment by longbai** [comment]
就是一个流，不是一个文件？

**Comment by nouh** [comment]
就是可以把一个stream pipe给这个上传的sdk，比如一个文件流， 而不是非要传一个文件地址

**Comment by longbai** [comment]
明白了，我们会考虑下

**Comment by longbai** [comment]
@bruceCzK 建议用户直接上传到七牛，再回调你们这边。浏览器可以用https的域名 up.qbox.me 上传

**Comment by bruceCzK** [comment]
好的，多谢。
另外我看了下源码，`io.js` 里面的 `putReadable` 这个方法是可以直接上传流的吗？

**Comment by peaceful321** [comment]
是希望通过文件流的格式来上传是么，这个目前好像都是还不支持的；
主要是通过file 或者path  java & Android 中还有字节数组这样的参数格式来进行上传；

**Comment by jemygraw** [comment]
v7.0.2 已支持
