### ISSUE TITLE
上传图片出错!

### ISSUE THREAD

**Issue by Here21** [qiniu/nodejs-sdk#191]
{ code: -1,
   error: 
  { [RequestError: connect ECONNREFUSED]
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect',
    name: 'RequestError' } }

请问是什么原因?

**Comment by longbai** [comment]
看起来是连接服务器失败，可能是网络问题，请问现在还有问题么？

**Comment by Here21** [comment]
已解决
```
qiniu.conf.UP_HOST = 'http://up-z1.qiniu.com';
```
之前没写`http://`

还有,你们官方的nodeSDK文档,貌似写的并不全,还是我没找到,官方nodeSDK文档,上传只写了`qiniu.io.putFile`但是大多数情况都需要`qiniu.io.put`

**Comment by zxkane** [comment]
七牛服务今天是相当不稳定吗？

遇到类似的问题，部署文件到bucket的时候不停的遇到类似错误！

>    { [RequestError: connect ETIMEDOUT 115.231.183.168:80]
>      code: 'ETIMEDOUT',
>      errno: 'ETIMEDOUT',
>      syscall: 'connect',
>      address: '115.231.183.168',
>      port: 80,
>      name: 'RequestError' } }

是从华北的阿里ECS上上传文件。已经设置七牛服务器为华北的，http://up-z1.qiniu.com。

**Comment by pangz1** [comment]
我这边遇到一个情况，部署到服务器上之后，生成的token 会报错 Key must be a buffer，请问这是什么原因？

**Comment by peaceful321** [comment]
可以看一下你 生成token 的关键代码么？这边测试下；

**Comment by jemygraw** [comment]
too long
