### ISSUE TITLE
有支持http_proxy 吗

### ISSUE THREAD

**Issue by shallwe** [qiniu/nodejs-sdk#192]
怎样实现通过http_proxy 上传文件过来，我的服务器在内网，不能直接上传，要通过代理，这个怎么做？
python的api，直接设置系统变量 http_proxy 就可以了，但是在node的api里怎么做？

**Comment by longbai** [comment]
下一个大版本有计划做，现在可以改下代码来支持

**Comment by jemygraw** [comment]
已发布v7.0.4版本，已支持，参考：https://github.com/qiniu/nodejs-sdk/blob/master/examples/http_https_proxy.js
