### ISSUE TITLE
在 Electron 中调用 qiniu.io.putFile 会创建新 Electron 实例

### ISSUE THREAD

**Issue by meathill** [qiniu/nodejs-sdk#212]
如题。

Electron 1.4.10~1.4.15
七牛 Node SDk 6.1.13

调用七牛云 SDK `qiniu.io.putFile()`，会启动一个新实例，原本的上传会暂停。这个时候关掉新实例，上传会继续。当前文件上传完成后，下个文件又会启动一个新实例。如此反复。

**Comment by jemygraw** [comment]
请更新到新版本v7.0.2，参考https://github.com/qiniu/nodejs-sdk/blob/master/examples/resume_upload_simple.js
