### ISSUE TITLE
是否支持断点续传？如何获得上传进度？

### ISSUE THREAD

**Issue by linshixiong** [qiniu/nodejs-sdk#215]
如题

**Comment by KevinOfNeu** [comment]
same issue

**Comment by GuGaobai1994** [comment]
https://github.com/qiniu/nodejs-sdk.v6/pull/234

**Comment by jemygraw** [comment]
参考：https://github.com/qiniu/nodejs-sdk/blob/master/examples/resume_upload_simple.js
设置putExtra的progressCallback可以获取上传进度。设置putExtra的resumeRecordFile可以支持断点续传。
