### ISSUE TITLE
put file with timeout 60000s

### ISSUE THREAD

**Issue by chenyuncai** [qiniu/nodejs-sdk#248]
ResponseTimeoutError: Response timeout for 60000ms, POST http://upload-z2.qiniup.com -1 (connected: true, keepalive socket: false)

when use FormUploader to upload a file, I got this error above.

Code:

> var formUploader = new qiniu.form_up.FormUploader(config);
> var putExtra = new qiniu.form_up.PutExtra();
> formUploader.putFile(uploadToken, keyName, filePath, putExtra, function(respErr, respBody, respInfo) {})
> 

where I can set the timeout option?   ^v^

Thanks.

**Comment by GuGaobai1994** [comment]
Hi, try to use resumeUploader for large files

**Comment by jemygraw** [comment]
conf.RPC_TIMEOUT=60000;
//单位毫秒，建议大文件用分片上传。

**Comment by Necmttn** [comment]
@jemygraw can you give any code example for;
`建议大文件用分片上传。 ??`

**Comment by chenyuncai** [comment]
The better way is using the qshell tool. Thanks...

**Comment by Necmttn** [comment]
I changed the timeout to `120000` no issue so far.

**Comment by jemygraw** [comment]
@Necmttn i am very confused that why nodejs will act like this when connecting to a remote server, in other languages, 60seconds is a very very long duration for a connect request to timeout, i think there must by something wrong with nodejs itself or the way we use it.

**Comment by Necmttn** [comment]
most likely the issue with Chinese internet I think, 
my code was broken because when i get close to 4 mb package limit with resumeuploader 60 seconds was already past so it was just throwing error.

**Comment by jemygraw** [comment]
@Necmttn but the timeout never happened in other languages under the same circumstance

**Comment by Necmttn** [comment]
@jemygraw   how about reducing the size of packages, I tried to make them 1 MB smaller packages. but qiniu server turn me error `unexpected package size`

**Comment by jemygraw** [comment]
@Necmttn you can not change the block size of the uploader, 4MB is defined in the protocol, you should not change it.
