### ISSUE TITLE
qiniu upload config error.

### ISSUE THREAD

**Issue by MarvinWilliam** [qiniu/nodejs-sdk#249]
<img width="714" alt="qq20170629-155936 2x" src="https://user-images.githubusercontent.com/10123167/27677386-1282cf8a-5ce4-11e7-8b8a-259083326509.png">

In my code I just do these.
Should I specify config.zone?
```
const config = new qiniu.conf.Config();
const formUploader = new qiniu.form_up.FormUploader(config);
const putExtra = new qiniu.form_up.PutExtra();

formUploader.put(getToken(type, key), key, content, putExtra, (err, body, response) => {
      if (err || response.statusCode !== 200) {
        reject(new Error(err || `upload qiniu response with code ${response.statusCode}.${JSON.stringify(body)}`));
      } else {
        resolve(body);
      }
    });
```

**Comment by MarvinWilliam** [comment]
After I modified the errored calbak, new errored throw like this.
I have never got this error before v7.0.4
<img width="1107" alt="qq20170629-161840 2x" src="https://user-images.githubusercontent.com/10123167/27678142-c0198722-5ce6-11e7-9e42-11ffd83e7bc4.png">

**Comment by GuGaobai1994** [comment]
hi , can you do the request in your chrome or curl
![image](https://user-images.githubusercontent.com/20764006/27681249-306087ec-5cf1-11e7-8275-2657bb274250.png)

**Comment by jemygraw** [comment]
you can use conf.zone , rather automatically detect the upload zone
