### ISSUE TITLE
zone.js: callback is not defined

### ISSUE THREAD

**Issue by cyij** [qiniu/nodejs-sdk#253]
qiniu/qiniu/zone.js:60
ReferenceError: callback is not defined

version: 7.0.4

**Comment by GuGaobai1994** [comment]
how to reappear?

**Comment by jemygraw** [comment]
这个好像是有问题，是获取zone失败的时候会出现，我们fix下。

**Comment by jemygraw** [comment]
fixed in 7.0.5
