### ISSUE TITLE
上传如何指定内网上传域名UpHost？

### ISSUE THREAD

**Issue by meteormatt** [qiniu/nodejs-sdk#255]
上传如何指定内网上传域名UpHost？比如`nbnb-gate-up.qiniu.com`

**Comment by GuGaobai1994** [comment]
客户端不建议使用内网地址，如需要指定可以修改qiniu.js中的qiniuuploadurls, 然后注释resetuploadurl

**Comment by meteormatt** [comment]
问题我是服务器端啊。

**Comment by GuGaobai1994** [comment]
var config = new qiniu.conf.Config();
var localFile = "/Users/jemy/Documents/qiniu.mp4";
var zone = new qiniu.conf.Zone([
        'up-na0.qiniup.com',
    ], [
        'upload-na0.qiniup.com',
    ], 'iovip-na0.qbox.me',
    'rs-na0.qiniu.com',
    'rsf-na0.qiniu.com',
    'api-na0.qiniu.com');

config.zone = zone;
var formUploader = new qiniu.form_up.FormUploader(config);

**Comment by GuGaobai1994** [comment]
可以新建一个zone传入

**Comment by meteormatt** [comment]
```javascript
var zone = new conf.Zone([
    'nbnb-gate-up.qiniu.com'
  ], [
    'upload.qiniup.com',
    'upload-nb.qiniup.com',
    'upload-xs.qiniup.com',
  ], 'iovip.qbox.me',
  'rs.qiniu.com',
  'rsf.qiniu.com',
'api.qiniu.com');
```
那这样应该就可以了。我只要改第一个参数就好了
