### ISSUE TITLE
createTimestampAntiLeechUrl生成的URL不正确

### ISSUE THREAD

**Issue by meteormatt** [qiniu/nodejs-sdk#256]
https://github.com/qiniu/nodejs-sdk/blob/a0c3e0ff0da128b59262fbe45c70ca2864847466/qiniu/cdn.js#L168

现在的createTimestampAntiLeechUrl生成的URL不正确。fileName是不需要urlencode的。
现在的代码会生成错误的URL
http://lq-qn-storage.gokuai.com/ea%2Fea9c3fb16cd9beb5b47b49af180a4f08ba44c31b.dat?attname=tim-bogdanov-97988.jpg&sign=5ae4c2aa5fe8c7dfeb10c492562955a6&t=598a91b0
实际上正确的URL应该是
http://lq-qn-storage.gokuai.com/ea/ea9c3fb16cd9beb5b47b49af180a4f08ba44c31b.dat?attname=tim-bogdanov-97988.jpg&sign=2f396ebfc58d2694da19b0679367d306&t=598a91b0

**Comment by meteormatt** [comment]
如果fileName='ea/ea9c3fb16cd9beb5b47b49af180a4f08ba44c31b.dat'，则样例结果错误。

**Comment by GuGaobai1994** [comment]
感谢提出，这边尽快修复，抱歉

**Comment by jemygraw** [comment]
fixed in 17a4cf798dbc475bf4f9bfbdfa59c5ee0beb6f30
