### ISSUE TITLE
通过sdk上传小于100kb文件,上传失败 ‘unexpected file size’

### ISSUE THREAD

**Issue by willnewii** [qiniu/nodejs-sdk#258]
大概范围是100kb以下的文件,就会上传失败.

![error](http://obfmtiyt5.bkt.clouddn.com/img/Cursor_%E5%92%8C_Developer_Tools_-_http___localhost_9080_.jpg)

**Comment by GuGaobai1994** [comment]
100kb的文件就不要用分片上传了，用表单上传比较合适

**Comment by willnewii** [comment]
哦哦.  是因为之前在表单上传没有看到有进度回调才用了分片上传.  
昨天看了一下文档,应该是64KB. createReadStream 默认读取的流大小是64KB. getZoneInfo又是个异步方法.导致在putReq方法里,其实文件已经读取结束.'data','end'两个事件会先后触发. rsStream.pause()并没有起效果.
