### ISSUE TITLE
node-sdk 不支持系统代理，因安全需要服务器需要通过代理上网

### ISSUE THREAD

**Issue by primewang** [qiniu/nodejs-sdk#259]
看你们用的"urllib": "2.22.0",
需要更更新urllib
哥哥们，快点更新哈，否则我没发用 @killme2008 @lidaobing @why404 @fengmk2 @ikbear

**Comment by primewang** [comment]
七牛版本是v7.0.6

**Comment by primewang** [comment]
用如下代码做测试时，一切正常
var urllib = require('urllib');
urllib.request('https://m.baidu.com', function (err, data, res) {
  if (err) {
    throw err; // you need to handle error
  }
  console.log(res);
});

**Comment by GuGaobai1994** [comment]
参考 example中的 http_https_proxy.js
![image](https://user-images.githubusercontent.com/20764006/29593582-b61142ca-87dd-11e7-98a7-4819ddfc043d.png)

**Comment by primewang** [comment]
为什么不用配置代理，现在这种方式需要每次改代码的 @jemygraw

**Comment by primewang** [comment]
这种方式，很不利于服务部署哈

**Comment by jemygraw** [comment]
你可以从配置文件里面读取出来ip设置到这里吧

**Comment by primewang** [comment]
@jemygraw 
配置如下：
var qiniu = require("qiniu");
const tunnel = require('tunnel-agent');
var mac = new qiniu.auth.digest.Mac(Config.qiniu.accessKey, Config.qiniu.secretKey);
var qiniuConfig = new qiniu.conf.Config();
var client = new qiniu.rs.BucketManager(mac, qiniuConfig);

    var proxyAgent = tunnel.httpOverHttp({
            proxy: {
                host: 'http://172.16.135.96',
                port: 3128
            }
            });
     qiniu.conf.RPC_HTTP_AGENT = proxyAgent;
     qiniu.conf.RPC_HTTPS_AGENT = proxyAgent;
     console.log('proxy: ' , qiniu.conf.RPC_HTTP_AGENT)
调用如下：
client.fetch(url, bucket, fileKey, function (err, ret) {
     if (!err) {
    } else {}
});

输出配置如下：
proxy:  TunnelingAgent {
  options: { proxy: { host: 'http://172.16.135.96', port: 3128 } },
  proxyOptions: { host: 'http://172.16.135.96', port: 3128 },
  maxSockets: Infinity,
  requests: [],
  sockets: [],
  _events: { free: [Function: onFree] },
  _eventsCount: 1,
  request: [Function: request] }
遇到：
 ConnectionTimeoutError: Connect timeout for 5000ms, GET https://uc.qbox.me/v2/query?ak=ywOqqctOOZIOnMRgpW-JudvZzElrbhUSk9uaFDt3&bucket=user-photos -2 (connected: false, keepalive socket: false)

**Comment by jemygraw** [comment]
你的代理不能支持https协议的请求，你可以指定 zone 参数避免出现自动查询的请求

**Comment by wizardforcel** [comment]
node 本身就不支持系统代理，你应该去它的仓库提
