### ISSUE TITLE
qiniu.io

### ISSUE THREAD

**Issue by Abunuo** [qiniu/nodejs-sdk#265]
没有 io 这个文件？

**Comment by GuGaobai1994** [comment]
? 是哪里遇到的

**Comment by sunsly1991** [comment]
感觉是这个报错。

报错位置代码是，官方文档里的demo，https://developer.qiniu.com/kodo/sdk/3828/node-js-v6#2
`var extra = new qiniu.io.PutExtra();`
报错是：
> TypeError: Cannot read property 'PutExtra' of undefined
