### ISSUE TITLE
建议urllib升级到2.24.0以支持使用系统代理

### ISSUE THREAD

**Issue by joyexpr** [qiniu/nodejs-sdk#271]
由于安全原因，请求须使用系统代理，目前urllib 2.24.0以上版本已支持，建议七牛库更新下

如果可以的话，希望七牛库里使用urllib时就能设置enableProxy为true，这样我们工程的启动脚本就不需要再另外增加URLLIB_ENABLE_PROXY参数。毕竟像request等库都respect env，默认使用系统HTTP_PROXY等参数，不理解为什么urllib不默认enableProxy为true，可能只是为了兼容旧版本行为

**Comment by GuGaobai1994** [comment]
可以先参考下https://github.com/qiniu/nodejs-sdk/blob/master/examples/http_https_proxy.js
