### ISSUE TITLE
文件下载自定义资源名BUG

### ISSUE THREAD

**Issue by wanzhou** [qiniu/nodejs-sdk#272]
attname如果包含特殊字符`;/?:@&=+$,#`在下载的时候会提示报错。
版本：`7.0.8`

**Comment by GuGaobai1994** [comment]
使用哪个方法报的问题可以贴下不

**Comment by wanzhou** [comment]
就是privateDownloadUrl 那个，fileName是 xxxxxxxx?attname=aaa#1.xlsx 这样的就有问题。底层的 publicDownloadUrl 用的是 encodeURI。

**Comment by GuGaobai1994** [comment]
收到，这边来复现处理下

**Comment by xialeistudio** [comment]
```
bucketManager.privateDownloadUrl(domain, key + "?attname="+encodeURIComponent('1#11#.xlsx'), 1510826748);
```
把你的资源手动encode即可，亲测可用，不过下载下来的文件名是encode之后的
