### ISSUE TITLE
数据流上传问题

### ISSUE THREAD

**Issue by MaelWeb** [qiniu/nodejs-sdk#275]
node koa2 通过数据流上传文件，上传成功但是文件为空

**Comment by GuGaobai1994** [comment]
抓包看下报文回比较清晰

**Comment by CrazyWr** [comment]
这个应该是数据流的问题,  数据流在上传前被使用过会被置空 或者 上传时 数据流还未写完到stream就开始上传了 具体指的是应该是在Writable stream的finish Event中上传 而不是 end Event 中上传数据
