### ISSUE TITLE
文件类型错误

### ISSUE THREAD

**Issue by fengbjhqs** [qiniu/nodejs-sdk#288]
qiniu: 7.1.3
按照文档操作，批量上传webpack生成的文件到空间，会有html，js，css等，

上传所有文件的类型，都会是 text/html，例如
http://p5dhe8rxg.bkt.clouddn.com/2018031417/static/css/app.e6bb11e033d6296530f8adda65f3832a.css
这个文件，手动修改为text/css，也不行，

文档里，上传文件没有手动定义文件类型的参数

**Comment by jemygraw** [comment]
不要共用var putExtra = new qiniu.resume_up.PutExtra();这个对象。
