### ISSUE TITLE
你们官网的文档也不更新一下，都是坑

### ISSUE THREAD

**Issue by akira-cn** [qiniu/nodejs-sdk#305]
https://developer.qiniu.com/kodo/sdk/3828/node-js-v6

```js
var qiniu = require("qiniu");
//需要填写你的 Access Key 和 Secret Key
qiniu.conf.ACCESS_KEY = 'Access_Key';
qiniu.conf.SECRET_KEY = 'Secret_Key';
//要上传的空间
bucket = 'Bucket_Name';
//上传到七牛后保存的文件名
key = 'my-nodejs-logo.png';
//构建上传策略函数
function uptoken(bucket, key) {
  var putPolicy = new qiniu.rs.PutPolicy(bucket+":"+key);
  return putPolicy.token();
}
//生成上传 Token
token = uptoken(bucket, key);
```

上面这样写最新版本的SDK根本用不了，直接报 invalid put policy options

要改成

```js
var qiniu = require("qiniu");
//需要填写你的 Access Key 和 Secret Key
qiniu.conf.ACCESS_KEY = 'Access_Key';
qiniu.conf.SECRET_KEY = 'Secret_Key';
//要上传的空间
bucket = 'Bucket_Name';
//上传到七牛后保存的文件名
key = 'my-nodejs-logo.png';
//构建上传策略函数
function uptoken(bucket, key) {
  var putPolicy = new qiniu.rs.PutPolicy({scope: bucket+":"+key});
  return putPolicy.uploadToken();
}
//生成上传 Token
token = uptoken(bucket, key);
```

**Comment by jemygraw** [comment]
你文档看错了，是这个 https://developer.qiniu.com/kodo/sdk/1289/nodejs
原来那个是旧的。

**Comment by qiqingfu** [comment]
https://developer.qiniu.com/kodo/sdk/3828/node-js-v6

**Comment by chuxia95588** [comment]
赞同，他们文档写的就是一滩屎一样，装13的。你直接弄个案例 copy过去就能用多好，非得写的13格那么高，变量都是var声明的还得瑟啥，一看就是一帮年纪大的写的，就怕大家直接下载下来就能用 ，真操蛋

**Comment by chuxia95588** [comment]
var qiniu = require('qiniu');
var accessKey = '';
var secretKey = '';
var mac = new qiniu.auth.digest.Mac(accessKey, secretKey);
var options = {
    scope: 'fsicong',
  };
var putPolicy = new qiniu.rs.PutPolicy(options);
var uploadToken=putPolicy.uploadToken(mac);
var config = new qiniu.conf.Config();
    config.zone = qiniu.zone.Zone_z2;
var localFile = "./octocat.png";
var formUploader = new qiniu.form_up.FormUploader(config);
var putExtra = new qiniu.form_up.PutExtra();
var key='111balabala.png';
var upload_to_qiniu = formUploader.putFile;

formUploader.putFile(uploadToken, key, localFile, putExtra, function(respErr,
  respBody, respInfo) {
  if (respErr) {
    throw respErr;
  }
  if (respInfo.statusCode == 200) {
    console.log(respBody);
  } else {
    console.log(respInfo.statusCode);
    console.log(respBody);
  }
});

这个直接能用  但是最好封装一下  并且改成ES6  不然可能多模块调用不适用

**Comment by GrinZero** [comment]
一群混蛋
