### ISSUE TITLE
使用pkg打包nodejs程序后会报错

### ISSUE THREAD

**Issue by Bruce-zxy** [qiniu/nodejs-sdk#307]
**Windows版本：** Windows 7 Service Pack 1
**命令行终端：** Windows Powershell
**Nodejs版本：** v8.9.4
**Pkg版本：** v4.3.4
**Qiniu版本：** v7.1.7

**异常截图：**
![image](https://user-images.githubusercontent.com/22904758/44523043-1692d300-a70b-11e8-9a1d-e88931fe5793.png)
**异常定位** package path -> "qiniu/index.js"
![image](https://user-images.githubusercontent.com/22904758/44523069-39bd8280-a70b-11e8-85da-e76ea8e4fe50.png)

**异常重现：**
1.将以下nodejs代码保存为“server.js”:

> const express = require('express');
> const qiniu = require('qiniu');
> const app = express();
> app.use('/', (req, res, next) => res.send('Hello World!') && next());
> var server = app.listen(8081, function() {
>     var host = server.address().address
>     var port = server.address().port
>     console.log("Server start successfully on http://${host}:${port}")
> })

2.安装依赖:
`npm install express qiniu --save`

3.启动服务，检查是否启动成功:
`node server`

4.启动成功后，在powershell中执行pkg命令打包nodejs程序:
`npx pkg -t win server.js`
or
`npm install -g pkg`
`pkg -t win server.js`

5.pgk打包成功后会在当前目录生成.exe文件，在powershell中执行exe文件启动程序:
`.\server.exe`

6.之前的问题就会在这里复现了

**Git Repo:**
你也可以直接克隆我已经建好的仓库，里面有两个分支，master分支是包含错误的，correct分支是配置正确的，克隆到本地后依次执行:
`npm install`
`node server`
`npm install -g pkg`
`pkg -t win server.js`
`.\server.exe`

url:[https://github.com/Bruce-zxy/pgk-qiniu-error](https://github.com/Bruce-zxy/pgk-qiniu-error)
git:[https://github.com/Bruce-zxy/pgk-qiniu-error.git](https://github.com/Bruce-zxy/pgk-qiniu-error.git)

**另外，我也在[pkg](https://github.com/zeit/pkg)的仓库里提了[issue#508](https://github.com/zeit/pkg/issues/508)，因为我不太确定这是qiniu的异常还是pkg的异常**

**Comment by yi-ge** [comment]
我也遇到了同样的问题。只有七牛存在这个问题。其它对象存储的SDK不存在。

**Comment by Bruce-zxy** [comment]
@yi-ge 提issue半年多了，连个label maker的人都没有。。。

**Comment by yi-ge** [comment]
@Bruce-zxy 我大概发现问题了。

Dynamic require may fail at run time, because the requested file is unknown at compilation time and not included into executable.

将七牛`index.js`文件改为：
```
module.exports = {
    auth: {
        digest: require('./qiniu/auth' + '/digest.js')
    },
    cdn: require('./qiniu/cdn.js'),
    form_up: require('./qiniu/storage/form.js'),
    resume_up: require('./qiniu/storage/resume.js'),
    rs: require('./qiniu/storage/rs.js'),
    fop: require('./qiniu/fop.js'),
    conf: require('./qiniu/conf.js'),
    rpc: require('./qiniu/rpc.js'),
    util: require('./qiniu/util.js'),
    zone: require('./qiniu/zone.js'),
    app: require('./qiniu/rtc/app.js'),
    room: require('./qiniu/rtc/room.js'),
    Credentials: require('./qiniu/rtc/credentials.js')
};
```

即可正常打包运行。

**Comment by Bruce-zxy** [comment]
@yi-ge 主要是不知道这个QINIU_COV环境变量意味着什么，如果知道的话，可以根据他们的需求来改了

**Comment by yi-ge** [comment]
@Bruce-zxy 估计是忘记删除的代码。😄

**Comment by hujiulong** [comment]
使用ncc构建也会有这个问题，现在的代码实际上已经修复了，什么时候能在npm上发布新版本？

**Comment by Bruce-zxy** [comment]
[最新版本7.3.0](https://github.com/qiniu/nodejs-sdk/releases/tag/v7.3.0)已经解决此问题
