### ISSUE TITLE
qiniu.io.putFile 没反应

### ISSUE THREAD

**Issue by bimohxh** [qiniu/nodejs-sdk#312]
版本 6.1.13

以前没问题，现在直接没反应，也不报错，就是卡在那了。话说你们这SDK升级也不能影响老的版本吧，新版比老版复杂了不少，简单点不好吗

**Comment by superTerrorist** [comment]
这个问题有解决吗？

**Comment by bimohxh** [comment]
已经转向阿里云OSS了

**Comment by FingerArt** [comment]
还没解决吗？上传到了100%，却不调用putFile的回调函数

**Comment by JemyCheung** [comment]
v7.3.0可以升级一下，从7.2.2看的话是都有回调的。6.1.13版本太老了，我们更新迭代的目的是解决问题 @bimohxh @superTerrorist @FingerArt
