### ISSUE TITLE
putStream 回调方法未执行

### ISSUE THREAD

**Issue by cc616** [qiniu/nodejs-sdk#329]
使用官方sdk，putStream的callback未执行
```
return new Promise((resolve, reject) => {
    const { buffer, originalname } = file
    const accessKey = fileConfig.qiniu.accessKey
    const secretKey = fileConfig.qiniu.secretKey
    const bucket = fileConfig.qiniu.bucket
    const mac = new qiniu.auth.digest.Mac(accessKey, secretKey)

    const options = {
      scope: bucket + ":" + originalname,
    }
    const putPolicy = new qiniu.rs.PutPolicy(options)
    const uploadToken = putPolicy.uploadToken(mac)

    const qiniuConfig = new qiniu.conf.Config()
    // 空间对应的机房
    qiniuConfig.zone = qiniu.zone.Zone_z2
    const formUploader = new qiniu.form_up.FormUploader(qiniuConfig)
    const putExtra = new qiniu.form_up.PutExtra()
    const readableStream = buffer // 可读的流
    formUploader.putStream(uploadToken, originalname, readableStream, putExtra, (respErr,
      respBody, respInfo) => {
      console.log(respErr)
      if (respErr) {
        console.log(respErr)
        reject(respErr)
      }
      if (respInfo.statusCode == 200) {
        console.log(respBody);
        resolve(respBody)
      } else {
        console.log(respBody);
        reject(respBody)
      }
    })
  })
```
也尝试过putFile方法，同样不会进callback，只有put方法能成功

**Comment by pinguo-zhangzhi** [comment]
callback成功或者失败的回调方法没有执行，我看过SDK的源代码了，是有问题的，我已经修复了这个问题，并且提交给七牛的技术人员了，但是还没有更新，如果你有需要的话，可以找我要修改后的源代码

**Comment by pinguo-zhangzhi** [comment]
> 使用官方sdk，putStream的callback未执行
> 
> ```
> return new Promise((resolve, reject) => {
>     const { buffer, originalname } = file
>     const accessKey = fileConfig.qiniu.accessKey
>     const secretKey = fileConfig.qiniu.secretKey
>     const bucket = fileConfig.qiniu.bucket
>     const mac = new qiniu.auth.digest.Mac(accessKey, secretKey)
> 
>     const options = {
>       scope: bucket + ":" + originalname,
>     }
>     const putPolicy = new qiniu.rs.PutPolicy(options)
>     const uploadToken = putPolicy.uploadToken(mac)
> 
>     const qiniuConfig = new qiniu.conf.Config()
>     // 空间对应的机房
>     qiniuConfig.zone = qiniu.zone.Zone_z2
>     const formUploader = new qiniu.form_up.FormUploader(qiniuConfig)
>     const putExtra = new qiniu.form_up.PutExtra()
>     const readableStream = buffer // 可读的流
>     formUploader.putStream(uploadToken, originalname, readableStream, putExtra, (respErr,
>       respBody, respInfo) => {
>       console.log(respErr)
>       if (respErr) {
>         console.log(respErr)
>         reject(respErr)
>       }
>       if (respInfo.statusCode == 200) {
>         console.log(respBody);
>         resolve(respBody)
>       } else {
>         console.log(respBody);
>         reject(respBody)
>       }
>     })
>   })
> ```
> 也尝试过putFile方法，同样不会进callback，只有put方法能成功
callback成功或者失败的回调方法没有执行，我看过SDK的源代码了，是有问题的，我已经修复了这个问题，并且提交给七牛的技术人员了，但是还没有更新，如果你有需要的话，可以找我要修改后的源代码

**Comment by cc616** [comment]
谢谢，已经解决了，暂时不需要了

**Comment by FingerArt** [comment]
@cc616 请问你怎么解决的？我使用 `putFile` 也不会调用callback

**Comment by cc616** [comment]
@FingerArt 一种是用的老文档的方法，这个是同事提供的，应该是七牛云之前的文档，我也没在官方找到具体的文档，上传路径好像是https://up-z2.qiniup.com
request.post(uploadUrl)
      .field('key', key)
      .field('name', name)
      .field('token', token)
      .attach('file', buffer, file)
      .set('Accept', 'application/json')
      .end((err, data) => {})
第二种还是官方最新的node sdk，用的是putStream，前提是你需要把文件先传到本地，然后用fs去读再调用putStream存到七牛云

**Comment by helloyou2012** [comment]
同 #323

**Comment by lhj233** [comment]
同样使用`putFile`不会调用回调，只有当路径错误时会调用。。我服了 版本号`@7.2.2`
