### ISSUE TITLE
内存不够，创建Buffer会使程序抛出异常

### ISSUE THREAD

**Issue by manooog** [qiniu/nodejs-sdk#339]
https://github.com/qiniu/nodejs-sdk/blob/131573a95d08773b5bd72b83cf0b07c9a4ee06bc/qiniu/storage/form.js#L155

这里构建的 crc32 字段是必须的吗？有没有其他方式绕过构建 Buffer 的过程。

**Comment by Lukunlin** [comment]
这个应该是你代码写得有问题。要么是你的文件流太大了，无法做到单文件上传的话可以试试分片。
