### ISSUE TITLE
使用putFile将文件上传后访问外链返回的content-type与文件的mimeType不同

### ISSUE THREAD

**Issue by fireairforce** [qiniu/nodejs-sdk#343]
我使用sdk文档里面的`putFile` API 去进行文档的上传，上传了几个`css`文件，传上去之后，有的`css`文件的文件类型在存储控制台显示的是`text/css`,但是使用外链去访问的时候，会发现外链返回的`Content-Type`为`application/javascript`,会导致`css`无法正常显示:

![~DBW6KZ2ZH30)NLR 1RXW~2](https://user-images.githubusercontent.com/32598811/66017053-c3916f00-e50b-11e9-8313-7c2861ca148c.png)
例如图片上面自己开发的一个网站的打印日志所示。同时在上传文件的时候有修改文件的`mimeType`

**Comment by yuzhanglong** [comment]
冒昧打扰。请问您解决了这个问题了吗，该怎么处理。。。我也遇到了QAQ

**Comment by yuzhanglong** [comment]
> 冒昧打扰。请问您解决了这个问题了吗，该怎么处理。。。我也遇到了QAQ.

刚刚解决了。
过程复现：我第一次上传某个文件没有考虑**mimeType**，第二次重新打包（由于没有修改代码，css打包的文件名（hash值）还是和上次相同的），上传加了**mineType**,仍然失效。
猜测:  由于七牛这边的服务器对**同名文件**做了一些缓存措施，导致文件类型没有及时更新。
解决方案：webpack打包时将content hash的长度修改一下（目的是让打包的文件名和上次的不同），然后再正确设置**mineType**即可。

**Comment by fireairforce** [comment]
我当时是把懒加载取消了QuQ https://github.com/fireairforce/Cloud/issues/1#issuecomment-538649921
