### ISSUE TITLE
使用pfop对视频进行裁剪封面图以后，然后手动调用prefop查询状态返回，成功以后直接返回截图的url地址，但是该地址404，还需等待一会儿图片才可以访问。

### ISSUE THREAD

**Issue by killdada** [qiniu/nodejs-sdk#344]
如上所述，截图如下
![1](https://user-images.githubusercontent.com/16487810/66208289-563a3580-e6e7-11e9-8f64-5b06b13a8ae0.png)
![2](https://user-images.githubusercontent.com/16487810/66208292-5803f900-e6e7-11e9-88cf-44f21de3962f.png)

针对这种手动查询的时候应该什么时候返回才好，或者是其他方式？

**Comment by bachue** [comment]
@killdada  pfop 支持 callback 的，可以使用服务器来接受 callback 后继续执行。
