### ISSUE TITLE
fs.createReadStream is not a function

### ISSUE THREAD

**Issue by sunwenli** [qiniu/nodejs-sdk#348]
![image](https://user-images.githubusercontent.com/14137823/66728538-27a32400-ee78-11e9-999e-4ff3d3629368.png)
antoher problem. guys

**Comment by helloyou2012** [comment]
@sunwenli 这是给 Node.js 用的，不是给前端用的，前端的是这个：https://github.com/qiniu/js-sdk

**Comment by sunwenli** [comment]
@helloyou2012 , 我这边是在 electron 写的桌面程序里调用七牛，出现上面的问题是因为调用时机不对。 
electron 里调用七牛需要把逻辑写在主进程里。上面截图里是写在了渲染进程里。
