### ISSUE TITLE
sendSms发短信unable to get local issuer certificate

### ISSUE THREAD

**Issue by chenkang084** [qiniu/nodejs-sdk#368]
查看源代码，使用的是https，以前都是正常的，今天调用api，报`unable to get local issuer certificate` ， 尝试修改源代码，改成http协议，可以发送成功，请问是不是七牛云服务器的https验证规则有修改呢？

**Comment by forrest-mao** [comment]
目前确认 https://sms.qiniuapi.com/ 的接口证书是正常的 
![image](https://user-images.githubusercontent.com/4973955/88519848-59f7c980-d025-11ea-9141-4c223bfdfa18.png)
您看是否可以本地安装 https://geotrust.tbs-certificats.com/GeoTrust_RSA_CA_2018.crt 七牛域名证书的 issuer 的 CA 证书，看下是否可以正常请求

**Comment by chenkang084** [comment]
多谢提醒，我查看了一下，是公司的网络block了七牛云的ssl , 我切换到手机热点，调用成功了。谢谢。
