### ISSUE TITLE
count获取标准存储的文件数量api应该如何调用

### ISSUE THREAD

**Issue by bboy-xp** [qiniu/nodejs-sdk#372]
sdk里面没有写到
只有api reference里面有请求示例
```
GET /v6/count?bucket=test07&begin=20170818140000&end=20170818151000&g=day HTTP/1.1
Host: api.qiniu.com
User-Agent: Go-http-client/1.1
Content-Type:application/x-www-form-urlencoded
Authorization: Qiniu j853F3bLkWl59I5BOkWm6q1Z1mZClpr9Z9CLfDE0:Zm5BbTRF8h6tpv9ZADAPOBPYmbg=
Accept-Encoding: gzip
```

这个在sdk里面有封装方法吗
不然不太清楚这个`Authorization`请求头应该怎么处理

**Comment by forrest-mao** [comment]
这里的 Authorization 使用的方法可以参考：https://github.com/qiniu/nodejs-sdk/blob/master/qiniu/util.js#L91 的 generateAccessTokenV2 方法，其中 mac 为密钥对对象（相关初始化方法为 https://github.com/qiniu/nodejs-sdk/blob/master/qiniu/auth/digest.js）
