### ISSUE TITLE
持久化数据处理中的 srcKey到底有何意义

### ISSUE THREAD

**Issue by code7s** [qiniu/nodejs-sdk#385]
这个 srcKey貌似写空间内任意一个文件名都可以，我封装方法时有时候压根不会用到这东西，这东西到底有什么作用，是不是可以写个自定义的值代替它呢？
<img width="988" alt="1" src="https://user-images.githubusercontent.com/48883244/122786151-963fb280-d2e6-11eb-8b58-0538c2f54a28.png">

**Comment by bachue** [comment]
@code7s  这不是用来选择处理空间里哪个文件的吗？pfop 命令都是针对一个文件的啊。
