### ISSUE TITLE
这个bug太坑了 元数据定义无法生效的问题  请修改

### ISSUE THREAD

**Issue by zcf19960503** [qiniu/nodejs-sdk#389]
目前的版本自定义传参无效
经过我不断调试找到了问题  气死
路径 \node_modules\_qiniu@7.4.0@qiniu\qiniu\storage\form.js

postForm.field(k, putExtra.params[k].toString());
改为
postForm.field(`x-qn-meta-${k.split('x:')[1]}`, putExtra.params[k].toString());

![13}E@T@%LSK27T )~550JPR](https://user-images.githubusercontent.com/40545975/152536146-2ff66e4c-b5a8-40d5-aca6-01c58392ba9f.png)

**Comment by lihsai0** [comment]
`putExtra.params` 是[自定义变量](https://developer.qiniu.com/kodo/1235/vars)而非元数据。

nodejs-sdk 之前不支持上传时添加元数据，新的 PR 已进行支持。
