### ISSUE TITLE
添加华东-浙江存储区域的 conf.Zone

### ISSUE THREAD

**Issue by china-bin** [qiniu/nodejs-sdk#392]
https://developer.qiniu.com/kodo/1671/region-endpoint-fq

由于不知道你们对象存储url的配置规则，所以并不好提pull request。
针对华东-浙江地区的存储我暂时使用的是这样的config
  config.zone = new conf.Zone(
    ['up-cn-east-2.qiniup.com', 'up-nb.qiniup.com', 'up-xs.qiniup.com'],
    ['upload.qiniup.com', 'upload-nb.qiniup.com', 'upload-xs.qiniup.com'],
    'iovip.qbox.me',
    'rs.qbox.me',
    'rsf.qbox.me',
    'api.qiniu.com'
  );

**Comment by LsyWeb** [comment]
唉，没人维护

**Comment by LsyWeb** [comment]
> 和 #400 重复了哈
但是从npm上下载的并没有华东-浙江地区的配置

**Comment by bachue** [comment]
@LsyWeb 嗯 目前还没有发布这个 PR，等到发布后就可以了。

**Comment by bachue** [comment]
@LsyWeb 另外，SDK 支持在不配置区域的情况下，通过自动查询来获取区域信息，所以其实不配置也可以。
