### ISSUE TITLE
[question] qhash如何在私有资源中使用

### ISSUE THREAD

**Issue by onichandame** [qiniu/nodejs-sdk#395]
### 问题
[文档](https://developer.qiniu.com/dora/1297/file-hash-value-qhash)中提到query后加?qhash/md5就能获得文件的md5码。但是我用往`privateDownloadUrl`的第二个入参（文件路径）后加了`?qhash/md5`，用返回的url拿到的还是文件内容，而非文件hash。

### 相关背景
1. `publicDownloadUrl`没有问题。
2. `privateDownloadUrl`入参中不加`?qhash/md5`，直接在返回的url后加的话会403报错

### 环境
qiniu: 7.3.2

**Comment by lihsai0** [comment]
@onichandame 您好，`privateDownloadUrl` 的参数含有签名。

`bucketManage.privateDownloadUrl` 方法暂不支持传入其他参数。

您可以尝试使用 `bucketManage.stat` 回调函数中的 `respBody.md5` 获取 md5

**Comment by lihsai0** [comment]
需要注意的是 `bucketManage.stat` 不保证能返回 md5。

已记录您的需求，后续会开发使 `privateDownloadUrl` 支持添加额外参数。

**Comment by onichandame** [comment]
@lihsai0 感谢解惑。`stat`尚未尝试，但文档里说不保证返回md5，却没有说明具体什么情况下不会返。请问有更详细的细节可供参考吗？

**Comment by bachue** [comment]
@onichandame 在分片上传的场景下，md5 是异步离线计算的，什么时候能返回我们也无法判断，但如果是表单上传，是立刻就可以返回的。
