### ISSUE TITLE
使用七牛 node 上传，第一次ok，连续两次，就报这个异常。

### ISSUE THREAD

**Issue by wsdo** [qiniu/nodejs-sdk#399]
"stack": "Error: read ECONNRESET\n\tat TCP.onStreamRead (node:internal/stream_base_commons:220:20)", "message": "read ECONNRESET, POST http://up-z1.qiniup.com/ -1 (connected: true, keepalive socket: true, socketHandledRequests: 1, socketHandledResponses: 0)\nheaders: {}", "errno": -54, "code": "ECONNRESET", "syscall": "read", "name": "ResponseError", "path": "/", "status": -1, "headers": {}, "res": { "status": -1, "headers": {} } }}

**Comment by wsdo** [comment]
目前，怎么解决呢？必现的， 第一个ok ，后面上传都不可以了

**Comment by lihsai0** [comment]
一般重试即可。

能否具体提供下具体环境信息？

操作系统、NodeJS 版本、SDK 版本等。看下能否稳定复现。

另外您这边到 http://up-z1.qiniup.com/ 的网络状态如何？
