### ISSUE TITLE
在egg中使用Promise始终返回404

### ISSUE THREAD

**Issue by A-birdFlyHigner** [qiniu/nodejs-sdk#420]
1、在使用qiniu SDK 拉取文件时，始终返回404，考虑异步回调的原因，也加了Promise包裹，但是结果并不如意：
<img width="642" alt="image" src="https://github.com/eggjs/egg/assets/23764742/7280010f-58c7-4e9d-ab6b-528431e2f0d5">

### Reproduction Repo

[bug.zip](https://github.com/eggjs/egg/files/13235150/bug.zip)

始终返回：
<img width="1375" alt="image" src="https://github.com/eggjs/egg/assets/23764742/fdad9c65-fa52-4ef4-b961-6c00e67cf041">

**Comment by lihsai0** [comment]
@A-birdFlyHigner 未能复现。

您提供的 zip 没有包含七牛的代码。

以下是基于您的 zip 修改，可正常工作的代码。

1. 安装 qiniu 包，例如 `npm install qiniu`
2. 修改 home.js
  ```javascript
  const qiniu = require('qiniu');
  const { Controller } = require('egg');

  // 仅作演示，请根据实际需求选择合适的位置获取 bucketManager
  const accessKey = process.env.QINIU_ACCESS_KEY;
  const secretKey = process.env.QINIU_SECRET_KEY;
  const bucketName = process.env.QINIU_TEST_BUCKET;
  const mac = new qiniu.auth.digest.Mac(accessKey, secretKey);
  const config = new qiniu.conf.Config();
  const bucketManager = new qiniu.rs.BucketManager(mac, config);
  
  // ....
  class HomeController extends Controller {
  // ...
    async list() {
      const { ctx } = this;
      const options = {
        limit: 10,
        prefix: '123/',
      };
      return new Promise((resolve, reject) => {
        bucketManager.listPrefix(bucketName, options, (err, respBody, respInfo) => {
          if (err) {
            reject(err);
            return;
          }
          console.log(respInfo);

          if (respInfo.statusCode !== 200) {
            ctx.throw(500, 'Internal Server Error');
            reject(new Error(`status: ${respInfo.statusCode}`));
            return;
          }
          console.log(respBody.items);
          ctx.body = {
            data: respBody.items,
          }
          resolve();
        });
      });
    }
  }
  ```
3. 修改 router.js
  ```javascript
  router.get('/list', controller.home.list); // 新增
  ```
4. `npm run dev`
5. 在浏览器访问对应地址


运行结果：

<img width="1324" alt="image" src="https://github.com/qiniu/nodejs-sdk/assets/17806506/d1197d95-e81c-45e9-ab57-8f4ad11ceb43">

---

既然已经使用 aync 函数，建议包装 Promise 时使用 await 操作：
```javascript
async list() {
  const { ctx } = this;
  const options = {
    limit: 10,
    prefix: '123/',
  };
  const {
    err,
    respBody,
    respInfo,
  } = await new Promise(resolve => {
    bucketManager.listPrefix(bucketName, options, (err, respBody, respInfo) => {
      resolve({ err, respBody, respInfo });
    });
  });
  if (err) {
    ctx.throw(500, new Error('internal err'));
    console.log(err, respInfo);
    return;
  }
  if (!respInfo || respInfo.statusCode !== 200) {
    ctx.throw(500, new Error('internal err'));
    console.log(err, respInfo);
    return;
  }
  ctx.body = {
    data: respBody.items,
  };
}
```

---

若您有更多问题，请继续评论。

**Comment by A-birdFlyHigner** [comment]
> @A-birdFlyHigner 未能复现。
> 
> 您提供的 zip 没有包含七牛的代码。
> 
> 以下是基于您的 zip 修改，可正常工作的代码。
> 
> 1. 安装 qiniu 包，例如 `npm install qiniu`
> 2. 修改 home.js
> 
> ```js
> const qiniu = require('qiniu');
> const { Controller } = require('egg');
> 
> // 仅作演示，请根据实际需求选择合适的位置获取 bucketManager
> const accessKey = process.env.QINIU_ACCESS_KEY;
> const secretKey = process.env.QINIU_SECRET_KEY;
> const bucketName = process.env.QINIU_TEST_BUCKET;
> const mac = new qiniu.auth.digest.Mac(accessKey, secretKey);
> const config = new qiniu.conf.Config();
> const bucketManager = new qiniu.rs.BucketManager(mac, config);
> 
> // ....
> class HomeController extends Controller {
> // ...
>   async list() {
>     const { ctx } = this;
>     const options = {
>       limit: 10,
>       prefix: '123/',
>     };
>     return new Promise((resolve, reject) => {
>       bucketManager.listPrefix(bucketName, options, (err, respBody, respInfo) => {
>         if (err) {
>           reject(err);
>           return;
>         }
>         console.log(respInfo);
> 
>         if (respInfo.statusCode !== 200) {
>           ctx.throw(500, 'Internal Server Error');
>           reject(new Error(`status: ${respInfo.statusCode}`));
>           return;
>         }
>         console.log(respBody.items);
>         ctx.body = {
>           data: respBody.items,
>         }
>         resolve();
>       });
>     });
>   }
> }
> ```
> 
> 3. 修改 router.js
> 
> ```js
> router.get('/list', controller.home.list); // 新增
> ```
> 
> 4. `npm run dev`
> 5. 在浏览器访问对应地址
> 
> 运行结果：
> 
> <img alt="image" width="1324" src="https://user-images.githubusercontent.com/17806506/280180553-d1197d95-e81c-45e9-ab57-8f4ad11ceb43.png">
> 既然已经使用 aync 函数，建议包装 Promise 时使用 await 操作：
> 
> ```js
> async list() {
>   const { ctx } = this;
>   const options = {
>     limit: 10,
>     prefix: '123/',
>   };
>   const {
>     err,
>     respBody,
>     respInfo,
>   } = await new Promise(resolve => {
>     bucketManager.listPrefix(bucketName, options, (err, respBody, respInfo) => {
>       resolve({ err, respBody, respInfo });
>     });
>   });
>   if (err) {
>     ctx.throw(500, new Error('internal err'));
>     console.log(err, respInfo);
>     return;
>   }
>   if (!respInfo || respInfo.statusCode !== 200) {
>     ctx.throw(500, new Error('internal err'));
>     console.log(err, respInfo);
>     return;
>   }
>   ctx.body = {
>     data: respBody.items,
>   };
> }
> ```
> 
> 若您有更多问题，请继续评论。另外，请考虑您是否使用了代理，导致域名解析到了错误的 IP 地址。

这有个测试仓库
https://github.com/A-birdFlyHigner/test-egg

**Comment by lihsai0** [comment]
@A-birdFlyHigner 
这个 404 是您的 `notFoundHandler` 中间件没拿到 `ctx.body` 返回的，与七牛无关。您的代码没有没有设置 `ctx.body` 请按以下步骤修改您的业务逻辑：

请参考上面的代码修改 `QiniuService` 的 `getFileListByBucketAndPrefix` 使其返回文件列表。

修改 `QiniuController` 的 `getFileListByBucketAndPrefix` 使其为 async 函数，并通过 await 获取 `QiniuService` 的 `getFileListByBucketAndPrefix` 的结果。最后将结果写入到 `ctx.body` 中。

**Comment by A-birdFlyHigner** [comment]
> @A-birdFlyHigner 这个 404 是您的 `notFoundHandler` 中间件没拿到 `ctx.body` 返回的，与七牛无关。您的代码没有设置 `ctx.body` 请按以下步骤修改您的业务逻辑：
> 
> 请参考上面的代码修改 `QiniuService` 的 `getFileListByBucketAndPrefix` 使其返回文件列表。
> 
> 修改 `QiniuController` 的 `getFileListByBucketAndPrefix` 使其为 async 函数，并通过 await 获取 `QiniuService` 的 `getFileListByBucketAndPrefix` 的结果。最后将结果写入到 `ctx.body` 中。

其实在listPrefix的回调里面，已经和返回给我404了。我在Controller里面已经await了，建议的写法依旧不行
<img width="623" alt="image" src="https://github.com/qiniu/nodejs-sdk/assets/23764742/17a89dd3-0c8b-446b-b336-4a842cbc09b1">

**Comment by lihsai0** [comment]
@A-birdFlyHigner 您红框打印的是 `ctx.body`。`ctx.body` 此时还未赋值，当然没有内容。您截图代码七牛返回的信息在 `err`, `respBody`, `respInfo` 这三个变量中。

**Comment by A-birdFlyHigner** [comment]
> @A-birdFlyHigner 您红框打印的是 `ctx.body`，而 `ctx.body` 此时还未赋值，当然没有内容。您截图代码七牛返回的信息在 `err`, `respBody`, `respInfo` 这三个变量中。

哈哈哈，但是实际上notFoundHandler这个中间件已经给我赋值并返回过了，这么理下来看样子还是有些问题：

**Comment by A-birdFlyHigner** [comment]
> > @A-birdFlyHigner 您红框打印的是 `ctx.body`，而 `ctx.body` 此时还未赋值，当然没有内容。您截图代码七牛返回的信息在 `err`, `respBody`, `respInfo` 这三个变量中。
> 
> 但是实际上notFoundHandler这个中间件已经给我赋值并返回过了。。： ![image](https://user-images.githubusercontent.com/23764742/280585098-fb957203-7946-4de4-9751-234be10e0cf3.png) <img alt="image" width="1153" src="https://user-images.githubusercontent.com/23764742/280585380-063e1686-00d0-40a4-ae1a-55a7668c615c.png">

**Comment by lihsai0** [comment]
@A-birdFlyHigner 
Promise 风格的 API 是计划要做的，暂时还没有，十分抱歉。
试了一下，上面提供的封装方式在中间件下，也可以正常工作。应该是您自己的代码问题，请自行排查一下。

**Comment by A-birdFlyHigner** [comment]
> @A-birdFlyHigner Promise 风格的 API 是计划要做的，暂时还没有，十分抱歉。 试了一下，上面提供的封装方式在中间件下，也可以正常工作。应该是您自己的代码问题，请自行排查一下。

吐。。。。到最后发现是jwt中间件没有await next（） = =
<img width="497" alt="image" src="https://github.com/qiniu/nodejs-sdk/assets/23764742/c18848fe-642f-4227-9ead-2f859f6f92c7">
感谢耐心解答
