### ISSUE TITLE
在Deno Deploy上无法执行上传操作

### ISSUE THREAD

**Issue by champkeh** [qiniu/nodejs-sdk#428]
![image](https://github.com/qiniu/nodejs-sdk/assets/7316006/ca1e0017-0929-4f86-b85f-cff896328b2b)

上传操作部分代码如下：
```js
const token = getToken(opts.bucket)

const config = new qiniu.conf.Config()
const formUploader = new qiniu.form_up.FormUploader(config)
const putExtra = new qiniu.form_up.PutExtra()
putExtra.mimeType = opts.mimeType

return new Promise((resolve, reject) => {
    formUploader.put(token, opts.file, opts.content, putExtra, (err, body, resp) => {
        if (err) {
            reject(err)
        } else if (resp.status === 200) {
            resolve(body)
        } else {
            reject(new Error(body.error))
        }
    })
})
```

可能是由于Deno Deploy环境无法向系统写入临时文件，所以出现上面的报错信息。

请问有没有在无写入权限的服务器环境执行上传操作呢？

**Comment by lihsai0** [comment]
@champkeh 当前版本可以通过配置区域满足您的需求，具体有两种实现方式

第一种，通过直接配置上传的区域。优点：实现简单。缺点：无法根据不同 bucket 选择上传域名。

```javascript
const config = new qiniu.conf.Config({
    useHttpsDomain: true,
    regionsProvider: new qiniu.httpc.StaticRegionsProvider([
        // Region ID 参考 https://developer.qiniu.com/kodo/1671/region-endpoint-fq
        new qiniu.httpc.Region.fromRegionId('z0')
    ])
})
```

第二种，配置为直接查询上传区域。优缺点与第一种相反。

```javascript
const queryRegionsEndpoints = [qiniu.conf.QUERY_REGION_HOST]
    .concat(qiniu.conf.QUERY_REGION_BACKUP_HOSTS)
    .map(h => new qiniu.httpc.Endpoint(h, { defaultScheme: 'https' }))
const config = new qiniu.conf.Config({
    useHttpsDomain: true,
    regionsProvider: new qiniu.httpc.QueryRegionsProvider({
        accessKey: your_ak,
        bucketName: your_bucket,
        endpointsProvider: new qiniu.httpc.StaticEndpointsProvider(queryRegionsEndpoints)
    })
})
```

---

后续会看下优化支持更方便的配置缓存级别。

**Comment by champkeh** [comment]
按照第一种方式写的时候，会报 ts 类型错误：
![image](https://github.com/iu/nodejs-sdk/assets/7316006/24781df1-d2ed-420b-a128-4cd02d4a996b)

然后执行的时候也报 undefined 错误：

![image](https://github.com/qiniu/nodejs-sdk/assets/7316006/356de066-2fe1-4be2-8405-c6d0b96d56fb)

用的版本是 qiniu@7.8.0：

![image](https://github.com/qiniu/nodejs-sdk/assets/7316006/13bc8486-02a7-4bac-a1f7-f966f7a429a4)

我目前改用前端上传的那个 qiniu-js 包来上传了(需要在 deno 环境打个 xhr 的补丁)，不过不知道这两个包在上传方面有没有什么区别

**Comment by lihsai0** [comment]
@champkeh

您这边第一次反馈时，使用的是 7.11.0 版本。也是这个版本对区域查询引入了文件级别缓存与重构后的区域类型。

在 7.8.0 版本不应该遇到您第一次反馈的问题。如确定使用 7.8.0 请检查您的 Deno Deploy 流程，确保依赖版本与 yarn.lock 一致。

qiniu-js 与本仓库在表单上传上区别不大。

**Comment by champkeh** [comment]
哦哦谢谢，第二次我是在本地试的，应该是缓存的老版本，我再试一下新版本

**Comment by champkeh** [comment]
用7.11.0版本可以了，非常感谢！

不过稍微有点小瑕疵，就是 ts 类型会报这样一个警告：

![image](https://github.com/qiniu/nodejs-sdk/assets/7316006/ba88c2cd-6813-443b-8840-3d3ad6c392b9)

不知道是deno的问题还是这个库的问题，不过不影响使用

**Comment by lihsai0** [comment]
@champkeh 不要意思，手残了。请去掉 new。
