### ISSUE TITLE
Cannot read properties of undefined (reading 'needRetry')

### ISSUE THREAD

**Issue by yuyang1004** [qiniu/nodejs-sdk#434]
上次失败，再次上传报错。node16时正常，但node18时报错。
/data/app/jenkins/jenkins_home/workspace/data-platform_prod/node_modules/qiniu/qiniu/storage/resume.js:146
                    return retryable && context.result.needRetry();
                                                       ^

TypeError: Cannot read properties of undefined (reading 'needRetry')
    at Retrier.onBeforeRetry (/data/app/jenkins/jenkins_home/workspace/data-platform_prod/node_modules/qiniu/qiniu/storage/resume.js:146:56)
    at /data/app/jenkins/jenkins_home/workspace/data-platform_prod/node_modules/qiniu/qiniu/retry/retrier.js:67:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.2

**Comment by xlanghejianfeng** [comment]
me too！！！
TypeError: Cannot read properties of undefined (reading 'needRetry')

**Comment by xlanghejianfeng** [comment]
急急急！！！

**Comment by lihsai0** [comment]
@yuyang1004 @xlanghejianfeng 能否提供一个复现的 DEMO？

**Comment by yuyang1004** [comment]
> @yuyang1004 @xlanghejianfeng 能否提供一个复现的 DEMO？

https://www.npmjs.com/package/@puhaha/vite-plugin-upload-oss

上传的时候可以断一下网络，网络正常的情况下不会报错，只有网络有波动需要重试的时候才会报错

**Comment by yuyang1004** [comment]
> > @yuyang1004 @xlanghejianfeng 能否提供一个复现的 DEMO？
> 
> https://www.npmjs.com/package/@puhaha/vite-plugin-upload-oss
> 
> 上传的时候可以断一下网络，网络正常的情况下不会报错，只有网络有波动需要重试的时候才会报错

用的是V2机制

**Comment by yuyang1004** [comment]
> > @yuyang1004 @xlanghejianfeng 能否提供一个复现的 DEMO？
> 
> https://www.npmjs.com/package/@puhaha/vite-plugin-upload-oss
> 
> 上传的时候可以断一下网络，网络正常的情况下不会报错，只有网络有波动需要重试的时候才会报错

用的是V2机制
