### ISSUE TITLE
[feature] bucketManager.listPrefix没有时间排序

### ISSUE THREAD

**Issue by xygengcn** [qiniu/nodejs-sdk#440]
bucketManager.listPrefix没有最新时间排序，拉取列表很难受，要一页一页的翻

**Comment by lihsai0** [comment]
@xygengcn 

服务端限制，无法支持排序，短期内也没有计划支持排序。

建议对文件的 key（文件路径）做好管理，通过目录分类、时间前缀等方法满足业务需求。
